<?php
header('Content-Type: application/json');
echo json_encode([
    "ServiceNow IT Leadership Professional Certificate",
    "Introduction to IT Architecture",
    "Creating Your IT Strategy",
    "Program Management for IT Professionals",
    "Succeeding as a First-Time Tech Manager",
    "Strategic Focus for Managers",
    "Implementing a Data Warehouse with SQL Server 2022",
    "How to Own Your Career and Build Your Dream Job",
    "Confidence: How to Overcome Self-Doubt, Insecurity, and Fears",
    "Develop Your Data Analysis Skills",
    "Python Data Analysis",
    "How to Think Strategically",
    "Excel: Advanced Formulas and Functions",
    "Lean Foundations: Driving High-Performance Teams",
    "Developing a Learning Mindset",
    "SQL for Data Analysis (2020)",
    "Become a Data Analytics Specialist",
    "Career Essentials in Data Analysis by Microsoft and LinkedIn",
    "Learning Data Analytics Part 2: Extending and Applying Core Knowledge",
    "Data Cleaning in Python Essential Training",
    "Predictive Analytics Essential Training: Data Mining",
    "OneNote Essential Training",
    "Learning Microsoft 365 Copilot",
    "AI Challenges and Opportunities for Leadership",
    "SAP S/4HANA: Beyond the Basics",
    "Ideaflow: The Only Business Metric That Matters (Book Bite)",
    "Practical Creativity for Everyone",
    "Communicating with Executives",
    "Excel PivotTable Quick Tips",
    "Excel Formulas and Functions Quick Tips",
    "Data Ethics: Making Data-Driven Decisions",
    "Intelligent Automation for Project Managers",
    "Excel: Power Query (Get & Transform)",
    "Introduction to Data Warehouses",
    "Measuring Business Performance",
    "Empathy for Customer Service Professionals (2020)",
    "Django: Forms",
    "What Is Generative AI?",
    "Nano Tips for Digital Networking with Diana YK Chan",
    "Critical Thinking",
    "Finding Your Leadership Purpose with Doug Conant",
    "Excel Supply Chain Analysis: Solving Transportation Problems",
    "Excel: Creating a Basic Dashboard",
    "Learning Agility",
    "International Logistics",
    "How to Train Your Brain for Maximum Growth",
    "Financial Forecasting with Analytics Essential Training",
    "Excel: Creating Custom Functions with LAMBDA",
    "Introduction to Career Skills in Data Analytics",
    "How to Plan Your Website",
    "Python Functions for Data Science",
    "Role based learning GBM Managers",
    "Excel for Accounting",
    "Learning Data Analytics: 1 Foundations",
    "Learning Django",
    "Data Analytics: Graph Analytics",
    "Certified Analytics Professional (CAP) Cert Prep: Domains 5-7",
    "Certified Analytics Professional (CAP) Cert Prep: Domains 1-4",
    "The Non-Technical Skills of Effective Data Scientists",
    "Data Analytics for Students (2020)",
    "Digital Transformation in Supply Chains",
    "Leading Projects",
    "Learning SAP MM (Materials Management)",
    "SAP ERP: Beyond the Basics (2019)",
    "SAP ERP Essential Training",
    "Data-Driven Decision-Making for Business Professionals",
    "Excel: Creating a Dashboard with Power Query (Microsoft 365)",
    "Data Analytics for Business Professionals",
    "Excel: Power Pivot for Beginners",
    "A3 Problem Solving for Continuous Improvement",
    "Process Improvement Foundations",
    "Picking the Right Chart for Your Data",
    "Learning Excel: Data Analysis (2019)",
    "Managing and Analyzing Data in Excel (Office 365/Excel 2019) (2019)",
    "Statistics Foundations 3: Using Data Sets",
    "Excel: Productivity Tips",
    "Business Analytics Foundations: Descriptive, Exploratory, and Explanatory Analytics",
    "Python Projects",
    "Excel: Power Query for Beginners",
    "Running a Profitable Business: Understanding Cash Flow",
    "Excel: Dashboards for Beginners",
    "Thinking, Fast and Slow (Blinkist Summary)",
    "Root Cause Analysis: Getting to the Root of Business Problems",
    "Excel: Economic Analysis and Data Analytics (2017)",
    "Excel Supply Chain Analysis: Solving Inventory Problems",
    "15 Mistakes to Avoid in Data Science",
    "Relational Databases Essential Training",
    "Operational Excellence Foundations",
    "SAP Ariba Supply Chain Collaboration Overview",
    "Tips for Writing Business Emails",
    "Advanced SQL for Query Tuning and Performance Optimization (2019)",
    "Selling to the C-Suite",
    "Systems Thinking",
    "20 Nano Tips for Maximizing Excel with Mike Tholfsen",
    "Strategic Agility",
    "Artificial Intelligence and Business Strategy: Case Studies",
    "Psychological Safety: Clear Blocks to Innovation, Collaboration, and Risk-Taking",
    "Tony Schwartz on Managing Your Energy for Sustainable High Performance",
    "Business Analysis Foundations: Enterprise",
    "Communicating with Emotional Intelligence",
    "Using Python for Automation",
    "Processing Text with Python Essential Training",
    "Learning SAP MM (Materials Management) (2019)",
    "What Business Leaders Need to Know about Web3 (+ Metaverse)",
    "Business Analysis: Essential Tools and Techniques",
    "Learning to Be Promotable",
    "Python for Non-Programmers",
    "Supply Chain Foundations: Analytics",
    "How to Manage Your Manager",
    "Learning Minitab",
    "Six Sigma Foundations",
    "Python Quick Start (2019)",
    "People Analytics",
    "Telling Stories with Data",
    "SQL for Statistics Essential Training",
    "Statistics Foundations: 3",
    "Finance Foundations: Risk Management",
    "CompTIA Data+ (DA0-001) Cert Prep: Domain 3.0 Data Analysis",
    "Developing a Critical Thinking Mindset",
    "Blockchain Basics",
    "Excel Statistics Essential Training: 2 (2019)",
    "How to Find and Use Your Strengths",
    "Improving Your Judgment for Better Decision-Making",
    "Building a Home IT Lab (2020)",
    "Overcoming Decision-Making Traps",
    "Advanced SQL – Window Functions",
    "Data Strategy"
// Add all your titles here...
]);
?>